eclipsesource/cdtcloud-deploymentserver

packages/deployment-server/package.json
packages/deployment-server/src/connectors/queue.ts
packages/deployment-server/src/deployments/routes.ts
packages/deployment-server/src/deployments/service.ts
packages/deployment-server/src/server.ts
packages/deployment-server/test/artifact.spec.ts
packages/deployment-server/test/connector.spec.ts
packages/deployment-server/test/deployment.spec.ts
packages/deployment-server/test/deviceType.spec.ts

Open websockets for streaming device i/o

feat(deployment-server): Open WSS for deployments

---

.git_commit_template.txt
.github/pull_request_template.md

- Added PR template
- Added commit template file

feat: Add git commit template & PR template

---

packages/deployment-server/src/devices/service.ts
packages/deployment-server/test/device.spec.ts

Least loaded device now selects devices that don't have any deployment requests.
Previously, it was assumed getAvailableDevices would be used.
This is a preparation to remove the device status distinction between `available`, `deploying` and `running` entirely, as it can be derived off the deployment requests.

fix(deployment-server): Device selection queries

---

packages/deployment-server/src/connectors/queue.ts
packages/deployment-server/src/deployments/routes.ts
packages/deployment-server/test/connector.spec.ts
packages/deployment-server/test/deployment.spec.ts

- Send deploymeny request id
- Assert that the deployment message via ws contains the id

fix(deployment-server): Send deployment id

---

packages/device-connector/src/deployment-server/connection.ts
packages/device-connector/src/deployment-server/service.ts
packages/device-connector/src/devices/deployment.ts
packages/device-connector/src/devices/device.ts

- Queue for deployments
- Update deployment status
- Adjust updates of device status

feat(DeviceConnector): Add queue & update status of device and deployment correctly

---

packages/deployment-server/src/dashboard/index.ts
packages/deployment-server/src/dashboard/routes.ts

- Adds deployments/minute over the last 20 minutes for a live graph

feat(deployment-server): Prepare deployments/minute series

---

.dockerignore
Dockerfile

- Fix docker build (`docker build .`)
See how to
1. Run `docker build .`
2. Got the `CONTAINERID`
3. Ran `docker run -it -p 3001 --network=host -e NODE_ENV=production -e DATABASE_URL='postgresql://postgres:dev@0.0.0.0:5432/deploymentdb?schema=public' CONTAINERID`
4. Navigated to `localhost:3001` and checked logs/ui

fix(deployment-server): docker build

---

Dockerfile.devcon
README.md
docker-compose.yml
packages/theia-extension/cdtcloud/src/node/compilation-service.ts

- Add support for STM32 boards

feat(DeviceConnector): Support STM32 devices

---

.dockerignore
package.json
packages/deployment-server-ui/package.json
packages/theia-extension/browser-app/package.json
packages/theia-extension/cdtcloud/package.json
packages/theia-extension/cdtcloud/src/browser/cdtcloud-frontend-module.ts
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget/TypeSelect.tsx
yarn.lock

- Pin a react setup that doesn't mess with `@theia/core` and/or hoisting
- Add Cpp syntax highlighting
1. `yarn install && yarn run download:plugins`
2. `docker-compose up`
3. `yarn run dev`
4. Open Arduino workspace, see syntax highlighting in .ino files
5. Open console, then cdtcloud widget, notice a lack of complaints

feat: Search in workspace, syntax highlighting, react fix

---

docker-compose.yml
packages/deployment-server/src/connectors/queue.ts
packages/deployment-server/src/dashboard/routes.ts
packages/deployment-server/src/deployments/routes.ts
packages/deployment-server/src/deployments/service.ts
packages/deployment-server/src/devices/service.ts
packages/deployment-server/test/connector.spec.ts
packages/deployment-server/test/deployment.spec.ts
packages/device-connector/src/deployment-server/connection.ts
packages/device-connector/src/devices/device.ts
packages/theia-extension/cdtcloud/src/browser/cdtcloud-frontend-module.ts
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget/TypeSelect.tsx
packages/theia-extension/cdtcloud/src/browser/monitoring/DeploymentManager.ts
packages/theia-extension/cdtcloud/src/common/protocol.ts
packages/theia-extension/cdtcloud/src/node/compilation-service.ts
yarn.lock

Please refer to the individual commits (WIP)

theia-frontend/deployment-server: Styles, set up output, update device status, compose setup

---

packages/device-connector/src/index.ts

- Add further handlers for kill signals
- Fixes unhandled kill signals in certain cases

fix(DeviceConnector): Fix unhandled kill signals

---

packages/deployment-server-ui/package.json
packages/deployment-server-ui/src/components/Dashboard/RecentDeploymentItem.tsx
packages/deployment-server-ui/src/components/Dashboard/RecentDeploymentList.tsx
packages/deployment-server-ui/src/main.tsx
packages/deployment-server-ui/src/util/iconLibrary.ts
yarn.lock

- Adds a button in the AdminUI Dashboard to show the id of recent deployments

feat(DeploymentServerUI): Add button to show deployment id

---

packages/deployment-server-ui/src/pages/Dashboard.tsx

- visual updates to dashboard
- using statistics to display data instead of current solution 
- coloring of UI elements
- added Icons to the different Statistics
- dashboard looks
- checkout branch, look at the dashboard

feat(dashboard): visual updates to dashboard

---

packages/deployment-server-ui/package.json
packages/deployment-server-ui/src/components/Dashboard/DeploymentsOverTimeGraph.module.scss
packages/deployment-server-ui/src/components/Dashboard/DeploymentsOverTimeGraph.tsx
packages/deployment-server-ui/src/pages/Dashboard.tsx
yarn.lock

- Using recharts to rework the deployments graph

feat(DeploymentServerUI): Deployments Graph

---

packages/deployment-server/src/device-types/index.ts
packages/deployment-server/src/device-types/service.ts

Adds a history of deployments/issues

feat(deployment-server): History for device types

---

packages/deployment-server-ui/src/components/Dashboard/RecentDeploymentItem.tsx
packages/deployment-server-ui/src/components/StatusTag.tsx
packages/deployment-server-ui/src/main.tsx
packages/deployment-server-ui/src/pages/TypeId.tsx

- fetch data for device type page
- Closes
-
1.
2.
3.
- update UI [ ]

feat(device-types/id): device types page

---

packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx

- change polling time for deployments table
- Closes
-
1.
2.
3.

refactor(change polling time)

---

README.md
packages/deployment-server/.gitignore
packages/deployment-server/package.json
packages/deployment-server/prisma/migrations/20220131180212_set_pks/migration.sql
packages/deployment-server/prisma/schema.prisma
packages/deployment-server/src/dashboard/routes.ts
packages/deployment-server/src/deployment-artifacts/routes.ts
packages/theia-extension/cdtcloud/src/browser/cdtcloud-frontend-module.ts
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx
packages/theia-extension/cdtcloud/src/browser/monitoring/DeploymentManager.ts
packages/theia-extension/cdtcloud/src/common/protocol.ts
packages/theia-extension/cdtcloud/src/node/cdtcloud-backend-module.ts
packages/theia-extension/cdtcloud/src/node/compilation-service.ts
packages/theia-extension/cdtcloud/src/node/config-service.ts
packages/theia-extension/cdtcloud/src/node/device-types-service.ts
yarn.lock

- Set the deployment server host for theia
- Deployment server: Use GCS (for i.e. containerized deployments)

GCS blobs, config via env

---

packages/deployment-server-ui/src/pages/Devices.tsx

- added auto updating to Devices Page
- Closes
-
1. please test by connecting/disconnecting a device while on the page

feat(devices-UI): add auto updating to devices page

---

packages/deployment-server-ui/src/components/Graphs/DeploymentsGraph.tsx

- Graph for total deployments over time

feat(DeploymentServerUI): Graph for total deployments over time

---

packages/deployment-server-ui/package.json
packages/deployment-server-ui/src/Colors.module.scss
packages/deployment-server-ui/src/pages/Devices.module.scss
packages/deployment-server-ui/src/pages/Devices.tsx
packages/deployment-server-ui/src/util/iconLibrary.ts
yarn.lock

- Connected devices will not show unavailable devices anymore
- Add deploy amounts per device

feat(DeploymentServerUI): Connected Devices Table Changes

---

.docker/device-connector/env
packages/device-connector/.env

- Use the hosted deployment server

fix(device-connector): Point to hosted deployment server

---

packages/deployment-server-ui/src/pages/Dashboard.tsx
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget/TypeSelect.tsx

- changed all "Board" occurrences in the frontend with "Device" 
- Closes
-
1.
2.
3.

style(rename board to device)

---

packages/deployment-server-ui/src/pages/Dashboard.tsx
packages/deployment-server-ui/src/pages/Deployments.tsx

- update the device types count in dashboard
- Closes
-
1.
2.
3.

Updates frontend

---

packages/deployment-server-ui/package.json
packages/deployment-server-ui/src/pages/Types.tsx
packages/deployment-server/package.json
packages/deployment-server/prisma/seed.ts
yarn.lock

- Add a simple searchbar in `/device-types`

Search for device types

---

packages/deployment-server-ui/src/pages/Devices.tsx

- Hackfix for fetch blocking filters
- Filters reset to their given value due to new data fetches

fix(DeploymentServerUI/Devices): Hackfix for fetch blocking filters

---

packages/deployment-server-ui/src/pages/TypeId.tsx

- Number of devices in the DeviceType page will not longer count unavailable devices

fix(DeploymentServerUI/Type): Fix number of devices of type

---

packages/deployment-server-ui/src/pages/Types.tsx

fix(deployment-server-ui): Initial device types

---

packages/deployment-server-ui/src/pages/Types.tsx

fix(deployment-server-ui): device-types: Extract title

---

packages/deployment-server-ui/src/pages/Dashboard.tsx
packages/deployment-server-ui/src/pages/TypeId.tsx

fix(deployment-server-ui): fix for demo

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

- Add GitHub Issue Templates for Bugs and Feature Requests
Closes #93

feat: Add GitHub Issue Templates

---

packages/deployment-server-ui/src/pages/Devices.tsx

- logical error in code was fixed, that resulted in an error in the frontend of connected devices
- Closes #105 
- ran application and opened Connected Devices Tab on the environment of the Deployment Server UI
1. start deployment-server-ui 
2. go to Connected Devices
3. Now a table should be shown with the connected devices (instead of a white screen)

Devices bug fix

---

.github/workflows/codestyle.yaml
.github/workflows/docker_build.yaml
.github/workflows/linux_build.yaml
Dockerfile
apps/docker/docker.ts
packages/device-connector/test/rpc-sample.spec.ts

- Move and modify core CI build
- Add Docker CI build
- Add codestyle CI
- Fix device-connector CI test
- Closes #96 
- Closes #90
1. Check working GitHub Actions

feat(CI): Add various CI scripts

---

packages/deployment-server-ui/src/services/MonitoringService.ts
packages/deployment-server-ui/src/services/WebsocketService.ts
packages/deployment-server/src/deployment-artifacts/routes.ts
packages/deployment-server/src/util/app.ts

- Adds support for Remote Deployments when using proxies
- Adds support for Remote Deployments when using GCS
- Fixes an issue where Websockets don't use a secure connection with certain browsers
- Fixes an issue with the Device Images when using proxies
- Closes #95 
- Remotely deployed an artifact and checked the AdminUI progress and pages
1. Start a device-connector and connect it to a remotely running deployment-server (Host deployment.sanctum-dev.com can be used for test purposes)
2. Start Theia on a different client and configure the settings accordingly as well
3. Connect a device to the machine running the device-connector
4. Deploy code over Theia
`git fetch …

fix: Remote Setup

---

packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget.tsx
packages/theia-extension/cdtcloud/src/browser/cdtcloud-widget/TypeSelect.tsx

- added theia color scheme
- Closes #88
- added different deployments and changed theme
1. add deployments
3. go to theia settings
4. select different themes and check the tags

Color scheme
